apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: postgres
        image: fullstackappdb:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: pg-service
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
  - port: 5432
